---
name: Build Resume

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Nix
        uses: cachix/install-nix-action@v15

      - name: Run Nix Build
        run: nix build -L --verbose

      - name: Get current date for tag
        id: tag
        run: echo "::set-output name=tag::$(date '+%s')"

      - name: Create Tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ steps.tag.outputs.tag }}"

      - name: Upload PDF
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: "${{ steps.tag.outputs.tag }}"
          files: |
            result/resume.pdf
