---
name: Build Resume

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Nix
        uses: cachix/install-nix-action@v15

      - name: Cache Nix Store
        uses: actions/cache@v2
        with:
          path: |
            /nix/store/**
            /nix/var/nix/*/*
            /nix/var/nix/db/*
            /nix/var/nix/db/*/**
            !/nix/var/nix/daemon-socket/socket
            !/nix/var/nix/userpool/*
            !/nix/var/nix/gc.lock
            !/nix/var/nix/db/big-lock
            !/nix/var/nix/db/reserved
          key: ${{ hashFiles('flake.lock') }}

      - name: Run Nix Build
        run: nix build --verbose
      - name: Create Tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ github.event.repository.updated_at }}"
      - name: Upload PDF
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: "${{ github.event.repository.updated_at }}"
          files: |
            result/resume.pdf
